import React from 'react';
import { useTranslation } from 'react-i18next';
import { ClipboardDocumentIcon } from '@heroicons/react/24/outline';
import useMessage from '../hooks/useMessage.ts';

interface Task {
  id: number;
  title: string;
  description: string | null;
  [key: string]: any;
}

interface TaskDataBoxProps {
  task: Task;
}

const TaskDataBox: React.FC<TaskDataBoxProps> = ({ task }) => {
  const { t } = useTranslation();
  const { showMessage } = useMessage();

  // Extrahiere automatisch generierte Daten aus task.description oder task.metadata
  // Prüfe ob Task ein Lebenszyklus-Task ist
  const isLifecycleTask = task.title?.includes('ARL') || 
                          task.title?.includes('EPS') || 
                          task.title?.includes('Pension') || 
                          task.title?.includes('Caja') ||
                          task.description?.includes('lifecycle');

  // Versuche Daten aus description zu extrahieren (JSON-Format)
  let autoGeneratedData: Record<string, any> = {};
  
  if (task.description) {
    try {
      // Versuche JSON aus description zu extrahieren
      const jsonMatch = task.description.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        autoGeneratedData = JSON.parse(jsonMatch[0]);
      }
    } catch (e) {
      // Kein JSON gefunden, versuche strukturierte Daten zu extrahieren
      const lines = task.description.split('\n');
      lines.forEach(line => {
        const match = line.match(/([^:]+):\s*(.+)/);
        if (match) {
          const key = match[1].trim();
          const value = match[2].trim();
          autoGeneratedData[key] = value;
        }
      });
    }
  }

  // Wenn keine Daten gefunden wurden und es ein Lebenszyklus-Task ist, zeige Standard-Daten
  if (Object.keys(autoGeneratedData).length === 0 && isLifecycleTask) {
    autoGeneratedData = {
      taskType: task.title,
      description: task.description || t('lifecycle.noDataAvailable')
    };
  }

  const handleCopyData = async () => {
    try {
      const dataString = JSON.stringify(autoGeneratedData, null, 2);
      await navigator.clipboard.writeText(dataString);
      showMessage(t('lifecycle.dataCopied', { defaultValue: 'Daten in Zwischenablage kopiert' }), 'success');
    } catch (error) {
      console.error('Fehler beim Kopieren:', error);
      showMessage(t('lifecycle.copyError', { defaultValue: 'Fehler beim Kopieren' }), 'error');
    }
  };

  // Zeige Box nur wenn es ein Lebenszyklus-Task ist oder Daten vorhanden sind
  if (!isLifecycleTask && Object.keys(autoGeneratedData).length === 0) {
    return null;
  }

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-300 dark:border-gray-700 p-6 mb-4">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold flex items-center dark:text-white">
          <ClipboardDocumentIcon className="h-5 w-5 mr-2" />
          {t('lifecycle.autoGeneratedData', { defaultValue: 'Automatisch generierte Daten' })}
        </h3>
        <button
          onClick={handleCopyData}
          className="text-blue-600 dark:text-blue-400 hover:underline text-sm"
        >
          {t('lifecycle.copyData', { defaultValue: 'Daten kopieren' })}
        </button>
      </div>
      <div className="space-y-2">
        {Object.keys(autoGeneratedData).length > 0 ? (
          Object.entries(autoGeneratedData).map(([key, value]) => (
            <div key={key} className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2">
              <span className="font-medium w-full sm:w-1/3 dark:text-gray-300">
                {t(`lifecycle.${key}`) || key}:
              </span>
              <span className="text-gray-600 dark:text-gray-400 flex-1 break-words">
                {typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value)}
              </span>
            </div>
          ))
        ) : (
          <div className="text-gray-500 dark:text-gray-400 text-sm">
            {t('lifecycle.noDataAvailable', { defaultValue: 'Keine automatisch generierten Daten verfügbar' })}
          </div>
        )}
      </div>
    </div>
  );
};

export default TaskDataBox;

