# Migration created at 2025-03-20 00:00:00
# --->scaffold

# --->schema
# This is your Prisma schema file,
# learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

# --->schema 